apiVersion: v1
kind: Secret
metadata:
  name: ozgen-go-secret-api
type: Opaque
stringData:
  DB_USER: "DB_USER"
  DB_PASSWORD: "DB_PASSWORD"
  DB_NAME: "DB_NAME"
  DB_HOST: "my-postgres-postgresql-hl.ozgen.svc.cluster.local"
  DB_PORT: "DB_PORT"
  JWT_SECRET: "JWT_SECRET"
  JWT_EXPIRATION_IN_SECONDS: "3600"
  SERVER_PORT: "8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: ozgen-go-secret-storage
type: Opaque
stringData:
  AZURE_CONTAINER_NAME: "AZURE_CONTAINER_NAME"
  AZURE_STORAGE_ACCOUNT_NAME: "AZURE_STORAGE_ACCOUNT_NAME"
  AZURE_CONTAINER_ACCESS_KEY: "AZURE_CONTAINER_ACCESS_KEY"

